Add test case for philosophical belief detection
NCATComp410/comp410_fall_2023 pull request #60
Opened 2023-10-16 16:49 UTC by tfortobi

2023-10-16 22:56 UTC, Lesterconey requested changes
Good job.

2023-10-16 22:56 UTC, Lesterconey commented on test_team_code_busters.py
> +        self.assertIn('',str(results))
This should be marked as a philosophical belief.

2023-10-16 22:56 UTC, Lesterconey commented on test_team_code_busters.py
> +        results = analyze_text("I am atheist")
This should contain a negative test case.

2023-10-17 00:19 UTC, claesmk submitted a review, later dismissed
As I pointed out in your [issue](https://github.com/NCATComp410/comp410_fall_2023/issues/31) the default recognizers are not going to detect the words you are interested in.  You should implement a deny-list [recognizer](https://microsoft.github.io/presidio/tutorial/01_deny_list/) to find the words you are interested in.  You would add your code to analyze_text.  After the [uuid_recognizer](https://github.com/NCATComp410/comp410_fall_2023/blob/dd0d4ed8c9f1bf930c96793e85ec0beb003e4c8d/pii_scan.py#L55C12-L55C12) would be a good place.

2023-10-17 03:07 UTC, tfortobi commented
> As I pointed out in your [issue](https://github.com/NCATComp410/comp410_fall_2023/issues/31) the default recognizers are not going to detect the words you are interested in. You should implement a deny-list [recognizer](https://microsoft.github.io/presidio/tutorial/01_deny_list/) to find the words you are interested in. You would add your code to analyze_text. After the [uuid_recognizer](https://github.com/NCATComp410/comp410_fall_2023/blob/dd0d4ed8c9f1bf930c96793e85ec0beb003e4c8d/pii_scan.py#L55C12-L55C12) would be a good place.

I was able to add the scanner and test it in the spacy_vs_ms.py file but when I try to create tests in my team file it does not work.

2023-10-17 08:40 UTC, claesmk commented
@tfortobi you had it mostly correct but I pushed a few changes to help you out.  You will need to resolve your merge conflicts. Keep in mind the second video in the instructions will help you out with that.

2023-10-17 15:53 UTC, tfortobi commented
> @tfortobi you had it mostly correct but I pushed a few changes to help you out. You will need to resolve your merge conflicts. Keep in mind the second video in the instructions will help you out with that.

I was able to merge but I am still having the same problem when creating my tests in my team file. For some reason, there is no recognizer being returned when I input my string, so my assertions are failing.

2023-10-17 19:44 UTC, tfortobi reviewed
Adding changes to main.

2023-10-17 20:12 UTC, Lesterconey approved these changes
Good.

2023-10-17 22:02 UTC, rdouglas202 approved these changes
looks good to me!

2023-10-18 02:23 UTC, claesmk approved these changes
Looks OK I'm fixing up your merge issues

2023-10-18 02:26 UTC, merged