Implemeneted Birth date Detection
NCATComp410/comp410_fall_2023 pull request #65
Opened 2023-10-17 00:46 UTC by tolanism

2023-10-17 01:23 UTC, claesmk requested changes
Your code is not actually detecting anything.  If you do not want to implement the custom recognizer discussed in your issue, you should at least look for the DATE_TIME entity which would at least indicate a date is present.

2023-10-17 01:48 UTC, tolanism commented
> Your code is not actually detecting anything. If you do not want to implement the custom recognizer discussed in your issue, you should at least look for the DATE_TIME entity which would at least indicate a date is present.

Is that why it's failing the pytest?

2023-10-17 02:11 UTC, claesmk commented
@tolanism I pushed some changes that fix your indentation issue, duplicated function, and added a DATE_TIME example.  You should be able to sync (push/pull) and see these changes in your codespace.

2023-10-17 02:12 UTC, claesmk submitted a review, later dismissed
Positive and negative cases for DATE_TIME detection are working. If you want to merge this, you can, or you can try to implement the custom recognizers suggested in your issue

2023-10-17 02:49 UTC, tolanism commented
> Positive and negative cases for DATE_TIME detection are working. If you want to merge this, you can, or you can try to implement the custom recognizers suggested in your issue

ok! Thank you. I've been reading [this] you suggested earlier (https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-6-using-context-words)
to understand the custom recognizers

2023-10-17 08:23 UTC, claesmk commented on test_team_code_busters.py
> +
Not sure what you were trying to do here?

2023-10-17 15:54 UTC, tfortobi approved these changes
Looks good to me, good job.

2023-10-17 18:04 UTC, Lesterconey submitted a review, later dismissed
Looks good.

2023-10-17 19:50 UTC, Lesterconey approved these changes

2023-10-17 23:29 UTC, chelseavuata submitted a review, later dismissed
Looks good!

2023-10-18 09:34 UTC, claesmk approved these changes
I resolved your merge conflicts and updated birthdate to BIRTHDATE to maintain consistency with other entity names

2023-10-18 09:34 UTC, merged